### ISSUE TITLE
Large Chunk Buffers dosn't seem to work on Linux

### ISSUE THREAD

**Issue by CGDoctor8** [jellysquid3/sodium-fabric#2]
glxinfo shows the current supported extensions
```
[doctor@localhost ~]$ glxinfo | grep ARB_copy_buffer
    GL_ARB_copy_buffer, GL_ARB_copy_image, GL_ARB_cull_distance, 
    GL_ARB_conservative_depth, GL_ARB_copy_buffer, GL_ARB_copy_image, 
```

Log:
https://paste.ee/p/ySIAF

![image](https://user-images.githubusercontent.com/39572468/73593568-7f37cf00-44fd-11ea-9da7-4a5518d0b27a.png)

**Comment by Fogrits** [comment]
I can't get it to work on Windows either

**Comment by ReplayCoding** [comment]
Seems to be disabled in the source code... I could be wrong though

**Comment by jellysquid3** [comment]
Large Chunk Buffers were a feature of the 1.14.x series of Sodium and remain to be ported to 1.15.x, so this option is disabled as it doesn't do anything. They are a high priority, though!
